;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "k8-deploy-promotion-policy")
(def path ".")
(def version "0.1.13")
(def tag "0.1.13")
(def generated-at "2021-03-23T23:06:20Z")
