;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "k8-deploy-promotion-policy")
(def path ".")
(def version "0.1.12")
(def tag "0.1.12")
(def generated-at "2021-03-20T01:20:56Z")
