;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "k8-deploy-promotion-policy")
(def path ".")
(def version "0.1.11")
(def tag "0.1.11")
(def generated-at "2021-03-19T23:07:18Z")
